<?php
/*
 * Language File: German
 *
 * Paste https://github.com/boxlabss/PASTE
 * demo: https://paste.boxlabs.uk/
 *
 * https://phpaste.sourceforge.io/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See LICENCE for more details.
 */

$lang = array();

$lang['banned'] = "Sie wurden auf " . $site_name . " gesperrt.";
$lang['expired']        = "Der gesuchte Paste ist abgelaufen.";
$lang['pleaseregister'] = "<br><br> <a class=\"btn btn-default\" href=\"login.php\">Melden Sie sich an</a> oder <a class=\"btn btn-default\" href=\"login.php?action=signup\">registrieren Sie sich</a>, um einen neuen Paste zu erstellen. Das ist kostenlos.";
$lang['registertoedit'] = "<a class=\"btn btn-default\" href=\"login.php\">Melden Sie sich an</a> oder <a class=\"btn btn-default\" href=\"login.php?action=signup\">registrieren Sie sich</a>, um diesen Paste zu bearbeiten oder zu forken. Das ist kostenlos.";
$lang['editpaste'] = "Bearbeiten";
$lang['forkpaste'] = "Fork";
$lang['guestmsgbody'] = "<a href=\"login.php\">Melden Sie sich an</a> oder <a href=\"login.php?action=signup\">registrieren Sie sich</a>, um Ihre Pasten zu bearbeiten, zu löschen und zu verwalten.";
$lang['emptypastebin'] = "Keine Pasten zum Anzeigen.";
$lang['siteprivate'] = "Dieser Pastebin ist privat. <a class=\"btn btn-default\" href=\"login.php\">Anmelden</a>";
$lang['image_wrong'] = "Falsches CAPTCHA.";
$lang['missing-input-response'] = "Der reCAPTCHA-Antwortparameter fehlt. Bitte überprüfen Sie Ihre PASTE-Einstellungen.";
$lang['missing-input-secret'] = "Der reCAPTCHA-Geheimschlüssel fehlt. Bitte fügen Sie ihn in den PASTE-Einstellungen hinzu.";
$lang['invalid-input-response'] = "Der reCAPTCHA-Antwortparameter ist ungültig. Bitte erneut versuchen.";
$lang['invalid-input-secret'] = "Der reCAPTCHA-Geheimschlüssel ist ungültig oder fehlerhaft. Bitte prüfen Sie die PASTE-Einstellungen.";
$lang['empty_paste'] = "Sie können keinen leeren Paste veröffentlichen.";
$lang['large_paste'] = "Ihr Paste ist zu groß. Maximalgröße ist " . $pastelimit . " MB";
$lang['paste_db_error'] = "Speichern in der Datenbank nicht möglich.";
$lang['error'] = "Es ist ein Fehler aufgetreten.";
$lang['archive'] = "Archiv";
$lang['archives'] = "Paste-Archiv";
$lang['archivestitle'] = "Diese Seite enthält die 100 zuletzt erstellten öffentlichen Pasten.";
$lang['contact'] = "Kontakt";
$lang['full_name'] = "Vollständiger Name";
$lang['email'] = "E-Mail";
$lang['email_invalid'] = "Ihre E-Mail-Adresse scheint ungültig zu sein.";
$lang['message'] = "Ihre Nachricht ist erforderlich.";
$lang['login/register'] = "Anmelden oder Registrieren";
$lang['rememberme'] = "Angemeldet bleiben.";
$lang['mail_acc_con'] = "$site_name Kontobestätigung";
$lang['mail_suc'] = "Verifizierungscode wurde erfolgreich an Ihre E-Mail-Adresse gesendet.";
$lang['email_ver'] = "E-Mail bereits verifiziert.";
$lang['email_not'] = "E-Mail nicht gefunden.";
$lang['pass_change'] = "Ein Link wurde an Ihre E-Mail gesendet.";
$lang['notverified'] = "Konto nicht verifiziert.";
$lang['incorrect'] = "Benutzer/Passwort falsch";
$lang['missingfields'] = "Alle Felder müssen ausgefüllt werden.";
$lang['userexists'] = "Benutzername bereits vergeben.";
$lang['emailexists'] = "E-Mail bereits registriert.";
$lang['registered'] = "Ihr Konto wurde erfolgreich registriert.";
$lang['usrinvalid'] = "Der Benutzername darf nur Buchstaben und Zahlen enthalten.";
$lang['mypastes'] = "Meine Pasten";
$lang['pastedeleted'] = "Paste gelöscht.";
$lang['databaseerror'] = "Speichern in der Datenbank nicht möglich.";
$lang['userchanged'] = "Benutzername erfolgreich geändert.";
$lang['usernotvalid'] = "Benutzername ungültig.";
$lang['privatepaste'] = "Dies ist ein privater Paste.";
$lang['wrongpassword'] = "Falsches Passwort.";
$lang['pwdprotected'] = "Mit Passwort geschützter Paste";
$lang['notfound'] = "404 Nicht gefunden";
$lang['wrongpwd'] = "Falsches Passwort. Bitte erneut versuchen.";
$lang['myprofile'] = "Mein Profil";
$lang['profileerror'] = "Profilinformationen konnten nicht aktualisiert werden";
$lang['profileupdated'] = "Ihre Profilinformationen wurden aktualisiert";
$lang['oldpasswrong'] = "Ihr altes Passwort ist falsch.";
$lang['pastetitle'] = "Titel";
$lang['pastetime'] = "Erstellt am";
$lang['pastesyntax'] = "Syntax";
$lang['pasteviews'] = "Aufrufe";
$lang['wentwrong'] = "Etwas ist schiefgelaufen.";
$lang['versent'] = "Eine Bestätigungs-E-Mail wurde an Ihre Adresse gesendet.";
$lang['modpaste'] = "Ändern oder Fork";
$lang['newpaste'] = "Neuer Paste";
$lang['highlighting'] = "Syntaxhervorhebung";
$lang['expiration'] = "Ablauf des Paste";
$lang['visibility'] = "Sichtbarkeit des Paste";
$lang['pwopt'] = "Passwort (optional)";
$lang['encrypt'] = "Alle Pasten werden in der Datenbank mit AES-256-CBC verschlüsselt";
$lang['entercode'] = "CAPTCHA eingeben";
$lang['almostthere'] = "Fast geschafft. Noch ein letzter Schritt.";
$lang['username'] = "Benutzername";
$lang['autogen'] = "Automatisch generierter Name";
$lang['setuser'] = "Benutzernamen festlegen";
$lang['keepuser'] = "Automatisch generierten Namen beibehalten? Sie können ihn einmal ändern.";
$lang['enterpwd'] = "Passwort eingeben";
$lang['totalpastes'] = "Gesamtzahl der Pasten:";
$lang['membtype'] = "Kontotyp:";
$lang['chgpwd'] = "Passwort ändern";
$lang['curpwd'] = "Aktuelles Passwort";
$lang['newpwd'] = "Neues Passwort";
$lang['confpwd'] = "Passwort bestätigen";
$lang['viewpastes'] = "Alle meine Pasten anzeigen";
$lang['recentpastes'] = "Neueste Pasten";
$lang['user_public_pastes'] = " — Pasten des Benutzers";
$lang['yourpastes'] = "Ihre Pasten";
$lang['mypastestitle'] = "Alle Ihre Pasten an einem Ort.";
$lang['delete'] = "Löschen";
$lang['highlighted'] = "Der folgende Text ist markiert. Drücken Sie Strg+C zum Kopieren (&#8984;+C auf dem Mac).";
$lang['download'] = "Herunterladen";
$lang['showlineno'] = "Zeilennummern ein/ausblenden";
$lang['copyto'] = "Text in die Zwischenablage kopieren";
$lang['rawpaste'] = "Rohtext";
$lang['membersince'] = "Mitglied seit: ";
$lang['delete_error_invalid'] = "Fehler: Paste nicht gelöscht, da er nicht existiert oder Ihnen nicht gehört.";
$lang['deleteaccount'] = 'Mein Konto löschen';
$lang['deletewarn'] = 'Dadurch werden Ihr Konto und alle Ihre Pasten dauerhaft entfernt. Dieser Vorgang kann nicht rückgängig gemacht werden.';
$lang['typedelete'] = 'Geben Sie DELETE zur Bestätigung ein.';
$lang['confirmdeletehint'] = 'Sie müssen DELETE (in Großbuchstaben) eingeben.';
$lang['cancel'] = 'Abbrechen';
$lang['confirmdelete'] = 'Löschen bestätigen';
$lang['wentwrong'] = 'Etwas ist schiefgelaufen.';
$lang['invalidtoken'] = 'Ungültiges CSRF-Token.';
$lang['not_logged_in'] = "Fehler: Sie müssen angemeldet sein, um das zu tun.";
$lang['public'] = "Öffentlich";
$lang['unlisted'] = "Nicht gelistet";
$lang['private'] = "Privat";
$lang['hello'] = "Hallo";
$lang['profile-message'] = "Dies ist Ihre Profilseite, auf der Sie Ihre Pasten verwalten können. Hier werden alle Ihre öffentlichen, privaten und nicht gelisteten Pasten angezeigt. Sie können Pasten auch von dieser Seite löschen. Andere Nutzer sehen nur die Pasten, die Sie öffentlich gemacht haben.";
$lang['profile-stats'] = "Einige Ihrer Statistiken:";
$lang['profile-total-pastes'] = "Gesamtzahl der Pasten:";
$lang['profile-total-pub'] = "Öffentliche Pasten gesamt:";
$lang['profile-total-unl'] = "Nicht gelistete Pasten gesamt:";
$lang['profile-total-pri'] = "Private Pasten gesamt:";
$lang['profile-total-views'] = "Gesamtaufrufe all Ihrer Pasten:";
$lang['embed-hosted-by'] = "gehostet von";
$lang['view-raw'] = "Rohansicht";
$lang['my_account'] = "Mein Konto";
$lang['guest'] = "Gast";
$lang['login'] = "Anmelden";
$lang['signup'] = "Registrieren";
$lang['forgot_password'] = "Passwort vergessen";
$lang['resend_verification'] = "Bestätigungs-E-Mail erneut senden";
$lang['or_login_with'] = "Oder anmelden mit";
$lang['login_with_google'] = "Google";
$lang['login_with_facebook'] = "Facebook";
$lang['already_have_account'] = "Sie haben bereits ein Konto?";
$lang['reset_password'] = "Passwort zurücksetzen";
$lang['new_password'] = "Neues Passwort";
$lang['send_reset_link'] = "Link zum Zurücksetzen senden";
$lang['email_verified'] = "E-Mail erfolgreich verifiziert. Sie können sich jetzt anmelden.";
$lang['invalid_code'] = "Ungültiger oder abgelaufener Code.";
$lang['pass_reset'] = "Passwort erfolgreich zurückgesetzt. Sie können sich jetzt anmelden.";
$lang['mail_error'] = "E-Mail konnte nicht gesendet werden.";
$lang['settings'] = "Einstellungen";
$lang['logout'] = "Abmelden";
$lang['49'] = "49";
$lang['50'] = "50";
$lang['account_suspended'] = "Konto gesperrt";
$lang['ajax_error'] = "Ajax-Fehler";
$lang['createpaste'] = "Paste erstellen";
$lang['email_not_verified'] = "E-Mail nicht verifiziert";
$lang['expired'] = "Abgelaufen";
$lang['forgot'] = "Vergessen";
$lang['fullname'] = "Vollständiger Name";
$lang['guestmsgtitle'] = "Hallo, Gast! Paste ist für Quellcode und allgemeinen Debug-Text gedacht.";
$lang['guestwelcome'] = "Willkommen, Gast";
$lang['invalid_credentials'] = "Ungültige Anmeldedaten";
$lang['invalid_email'] = "Ungültige E-Mail";
$lang['invalid_reset_code'] = "Ungültiger Reset-Code";
$lang['invalid_state'] = "Ungültiger Zustand";
$lang['invalid_username'] = "Ungültiger Benutzername";
$lang['login_required'] = "Anmeldung erforderlich";
$lang['login_success'] = "Anmeldung erfolgreich";
$lang['low_score'] = "Niedriger Score";
$lang['my-pastes'] = "Meine Pasten";
$lang['no_results'] = "Keine Ergebnisse";
$lang['password'] = "Passwort";
$lang['password_reset_success'] = "Passwort erfolgreich zurückgesetzt";
$lang['password_too_short'] = "Passwort zu kurz";
$lang['pastemember'] = "Mitglied";
$lang['pastes'] = "Pasten";
$lang['recaptcha_error'] = "reCAPTCHA-Fehler";
$lang['recaptcha_failed'] = "reCAPTCHA konnte nicht bestätigen, dass Sie kein Bot sind. Aktualisieren Sie die Seite und versuchen Sie es erneut.";
$lang['recaptcha_missing'] = "reCAPTCHA fehlt";
$lang['recaptcha_timeout'] = "reCAPTCHA-Zeitüberschreitung";
$lang['resend'] = "Erneut senden";
$lang['search'] = "Suchen";
$lang['search_results_for'] = "Suchergebnisse für";
$lang['signup_success'] = "Registrierung erfolgreich";
$lang['sort'] = "Sortieren";
$lang['sort_code_asc'] = "Code ↑";
$lang['sort_code_desc'] = "Code ↓";
$lang['sort_date_asc'] = "Datum ↑";
$lang['sort_date_desc'] = "Datum ↓";
$lang['sort_title_asc'] = "Titel ↑";
$lang['sort_title_desc'] = "Titel ↓";
$lang['sort_views_asc'] = "Aufrufe ↑";
$lang['sort_views_desc'] = "Aufrufe ↓";
$lang['submit_error'] = "Sende­fehler";
$lang['user_exists'] = "Benutzer existiert bereits";
$lang['views'] = "Aufrufe";
$lang['charsleft'] = "Zeichen übrig";
$lang['cancel'] = "Abbrechen";
$lang['postreply'] = "Antwort senden";
$lang['loginreply'] = "Zum Antworten anmelden";
$lang['reply'] = "Antworten";
$lang['logintocomment'] = "Melden Sie sich an, um mitzudiskutieren.";
$lang['nocomments'] = "Noch keine Kommentare. Seien Sie der Erste.";
$lang['commentexplain'] = "Markdown ist deaktiviert; Links werden automatisch erkannt.";
$lang['comments'] = "Kommentare";
$lang['postcomment'] = "Kommentar senden";
$lang['logintocomment'] = "Melden Sie sich an, um einen Kommentar zu schreiben.";
$lang['commentsdisabled'] = "Kommentare wurden deaktiviert.";
$lang['postedon'] = "Veröffentlicht am:";
$lang['size'] = "Größe:";
$lang['detected'] = "Erkannt";
$lang['viewdifferences'] = "Unterschiede anzeigen";
$lang['loadraw'] = "Rohtext laden";
$lang['detectedexplainlabel'] = "Wie wir die Sprache erkannt haben";
?>